name: snipfy

services:
  web:
    container_name: snipfy-web
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    networks:
      - snipfy

networks:
  snipfy:
    driver: bridge
